const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const {
  matchesAnyPattern,
  resolveProfileOperatingMode,
  extractSessionSummary,
  extractReviewResult,
  ensureNextSessionBlock,
  upsertSessionProtocolBlock
} = require('./session-protocol-utils');

const EXIT = {
  SUCCESS: 0,
  CRITICAL_FAILURE: 1,
  POLICY_VIOLATION: 2,
  QUALITY_GATE_FAILURE: 3
};

const SUPPORTED_FLAGS = new Set(['--json', '--dry-run', '--confirm-write', '--yes', '--airtable']);
const BUILD_ARTIFACT_PREFIXES = [
  'insights/',
  'assets/css/',
  // Built inner-page output directories (generated by build-inner-pages.js from _templates/)
  'what-we-do/',
  'how-we-work/',
  'about/',
  'contact/',
  'talks-events/',
  'programmes/',
  'design-system/',
];
const BUILD_ARTIFACT_FILES = new Set(['index.html', 'sitemap.xml']);

function parseArgs(argv) {
  const args = {
    json: false,
    dryRun: false,
    confirmWrite: false,
    yes: false,
    airtable: false
  };

  const unknown = [];
  for (const flag of argv) {
    if (!SUPPORTED_FLAGS.has(flag)) {
      unknown.push(flag);
      continue;
    }

    if (flag === '--json') args.json = true;
    if (flag === '--dry-run') args.dryRun = true;
    if (flag === '--confirm-write') args.confirmWrite = true;
    if (flag === '--yes') args.yes = true;
    if (flag === '--airtable') args.airtable = true;
  }

  return { args, unknown };
}

function run(command) {
  try {
    const stdout = execSync(command, { stdio: 'pipe' }).toString().trim();
    return { ok: true, stdout, code: 0 };
  } catch (error) {
    return {
      ok: false,
      stdout: error.stdout?.toString()?.trim() || '',
      stderr: error.stderr?.toString()?.trim() || '',
      code: error.status || 1,
      message: error.message
    };
  }
}

function shellQuote(input) {
  return `'${String(input).replace(/'/g, `'\\''`)}'`;
}

function timestamp() {
  const now = new Date();
  const pad = n => n.toString().padStart(2, '0');
  return `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}-${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`;
}

function formatDate(date) {
  return date.toISOString().split('T')[0];
}

function upsertClaudeLastSession(content, date, fallbackSummary) {
  // If the agent already wrote a "Last session:" line for today, preserve it.
  const existing = content.match(/\*\*Last session:\*\*\s*(\d{4}-\d{2}-\d{2})\s*—\s*(.+)/i);
  if (existing && existing[1] === date) {
    return content; // already set today — don't clobber
  }

  const line = `**Last session:** ${date} — ${fallbackSummary}`;
  if (/\*\*Last session:\*\*/i.test(content)) {
    return content.replace(/\*\*Last session:\*\*.*(?:\n|$)/i, `${line}\n`);
  }

  if (/## Current State/i.test(content)) {
    return content.replace(/## Current State\n+/i, `## Current State\n\n${line}\n\n`);
  }

  return `${content}${content.endsWith('\n') ? '' : '\n'}\n## Current State\n\n${line}\n`;
}

function extractNextSessionPriorities(claudeContent) {
  const match = claudeContent.match(/## Next Session Priorities\n([\s\S]*?)(?=\n##|$)/i);
  if (!match) return null;
  return match[1].trim();
}

function recentCommits(n = 8) {
  try {
    return execSync(`git log -${n} --oneline`, { stdio: 'pipe' }).toString().trim();
  } catch {
    return null;
  }
}

function loadSessionNotes(notesPath) {
  if (!fs.existsSync(notesPath)) return null;
  const raw = fs.readFileSync(notesPath, 'utf8').trim();
  // Demote the notes' own h2 headings (## Summary, ## Decisions, …) one level so they
  // nest under the log's "## Decisions / Findings" section instead of terminating it —
  // session-start.js extracts that section up to the next h2, so un-demoted notes meant
  // only the first sub-block (Summary) ever surfaced in the next session's brief (#82).
  return raw.replace(/^## /gm, '### ');
}

function buildSessionLog({ branch, headHash, date, isoDate, airtable, claudeContent, notesPath, reviewResult }) {
  const priorities = extractNextSessionPriorities(claudeContent);
  const commits = recentCommits(8);
  const notes = loadSessionNotes(notesPath);

  const decisionsSection = notes
    ? notes
    : '  - _Fill in `.claude/session-notes.md` before running session-end, or edit this log._';

  const prioritiesSection = priorities
    ? priorities.split('\n').map(l => `  ${l}`).join('\n')
    : '  1. _See CLAUDE.md → Next Session Priorities_';

  const commitsSection = commits
    ? commits.split('\n').map(l => `  ${l}`).join('\n')
    : '  _no commits found_';

  return [
    `# Session Log – ${isoDate}`,
    '',
    `- **Branch:** ${branch}`,
    `- **Git commit:** ${headHash}`,
    `- **Quality gates:** ✅ passed`,
    `- **Fresh-eyes review:** ${reviewResult ? reviewResult.split('\n')[0] : '_not recorded_'}`,
    `- **Airtable updates:** ${airtable ? 'requested (placeholder)' : 'skipped'}`,
    '',
    '## Recent commits this session',
    '',
    commitsSection,
    '',
    '## Decisions / Findings',
    '',
    decisionsSection,
    '',
    '## Next Session Priorities',
    '',
    prioritiesSection,
    '',
  ].join('\n');
}

function detectStalePriorities(claudeContent) {
  // Extract completed item labels from the ## Next section (lines containing ✅).
  // Expects format: `**Label — Description ✅ Complete**` — the bold label before
  // the first — or ✅ is used as the match key. Keep CLAUDE.md Next items in this format.
  const nextMatch = claudeContent.match(/## Next \(do in this order\)([\s\S]*?)(?=\n## |\n---)/i);
  if (!nextMatch) return [];

  const completedLabels = [];
  for (const line of nextMatch[1].split('\n')) {
    if (!line.includes('✅')) continue;
    const m = line.match(/\*\*([^*—]+?)(?:\s*[—✅])/);
    if (m) completedLabels.push(m[1].trim());
  }
  if (completedLabels.length === 0) return [];

  // Check the ## Next Session Priorities block for any of those labels
  const prioritiesMatch = claudeContent.match(/## Next Session Priorities\n([\s\S]*?)(?=\n## |$)/i);
  if (!prioritiesMatch) return [];

  const prioritiesText = prioritiesMatch[1].toLowerCase();
  return completedLabels.filter(label => prioritiesText.includes(label.toLowerCase()));
}

function loadProfile(profilePath) {
  if (!fs.existsSync(profilePath)) {
    return { error: `Missing protocol profile at ${profilePath}` };
  }

  try {
    const parsed = JSON.parse(fs.readFileSync(profilePath, 'utf8'));
    const resolved = resolveProfileOperatingMode(parsed);

    if (resolved.error) {
      return { error: resolved.error };
    }

    const profile = resolved.profile;
    if (!profile.version || !profile.git || !Array.isArray(profile.git.allowedBranchPatterns)) {
      return { error: 'Invalid protocol profile: missing required git policy fields.' };
    }
    return { profile, activeMode: resolved.activeMode };
  } catch (error) {
    return { error: `Failed to parse protocol profile: ${error.message}` };
  }
}

function askForConfirmation(message) {
  process.stdout.write(`${message} [y/N]: `);
  const buffer = Buffer.alloc(1024);
  const bytes = fs.readSync(process.stdin.fd, buffer, 0, buffer.length);
  const answer = buffer.toString('utf8', 0, bytes).trim().toLowerCase();
  return answer === 'y' || answer === 'yes';
}

function collectChangedPaths() {
  try {
    const stdout = execSync('git status --porcelain', { stdio: 'pipe' }).toString();
    return stdout
      .split('\n')
      .map(line => {
        const match = line.match(/^..\s(.+)$/);
        return match ? match[1].trim() : '';
      })
      .filter(Boolean);
  } catch {
    return [];
  }
}

function isAllowedArtifact(filePath) {
  if (BUILD_ARTIFACT_FILES.has(filePath)) return true;
  return BUILD_ARTIFACT_PREFIXES.some(prefix => filePath.startsWith(prefix));
}

const { args, unknown } = parseArgs(process.argv.slice(2));
if (unknown.length > 0) {
  console.error(`Unknown flag(s): ${unknown.join(', ')}`);
  process.exit(EXIT.CRITICAL_FAILURE);
}

if (args.dryRun && args.confirmWrite) {
  console.error('Invalid flags: --dry-run and --confirm-write cannot be combined.');
  process.exit(EXIT.CRITICAL_FAILURE);
}

const mode = args.dryRun ? 'dry-run' : args.confirmWrite ? 'write' : 'plan';
const warnings = [];
const errors = [];
const operations = [];

const profilePath = path.join('.session-protocol.json');
const profileResult = loadProfile(profilePath);
if (profileResult.error) {
  console.error(profileResult.error);
  process.exit(EXIT.CRITICAL_FAILURE);
}
const profile = profileResult.profile;
const activeMode = profileResult.activeMode || 'default';
operations.push({ step: 'operating_mode', status: 'ok', detail: activeMode });

const branchResult = run('git rev-parse --abbrev-ref HEAD');
if (!branchResult.ok) {
  console.error('Unable to detect current git branch.');
  process.exit(EXIT.CRITICAL_FAILURE);
}
const branch = branchResult.stdout;

if (!matchesAnyPattern(branch, profile.git.allowedBranchPatterns)) {
  console.error(`Branch '${branch}' is not allowed by session protocol policy.`);
  process.exit(EXIT.POLICY_VIOLATION);
}
operations.push({ step: 'branch_policy', status: 'ok', detail: branch });

const ts = timestamp();
const today = formatDate(new Date());
const logDir = profile.artifacts?.sessionLogDir || '.claude/sessions';
const logPath = path.join(logDir, `session-${ts}.md`);
const writeModeEnabled = mode === 'write';

if (mode === 'plan') {
  warnings.push('Safe-by-default mode: no writes, no commit, no push. Use --confirm-write to execute.');
}

const currentHead = run('git rev-parse HEAD');
const headHash = currentHead.ok ? currentHead.stdout : 'unknown';

const plannedManagedFiles = new Set(profile.docs?.managedFiles || []);
const allowedChangedPathPatterns = profile.sessionEnd?.allowedChangedPathPatterns || [];
const sessionBlockMarkers = {
  startMarker: profile.docs?.sessionProtocolBlock?.startMarker,
  endMarker: profile.docs?.sessionProtocolBlock?.endMarker
};

if (mode !== 'dry-run') {
  if (writeModeEnabled && !args.yes) {
    const approved = askForConfirmation(`Session-end write mode will modify files on branch '${branch}'. Continue?`);
    if (!approved) {
      console.error('Write operation cancelled by user.');
      process.exit(EXIT.POLICY_VIOLATION);
    }
  }
} else {
  operations.push({ step: 'dry_run', status: 'ok', detail: 'No writes or git mutations will be executed.' });
}

let qualityGateFailed = false;
const requiredCommands = profile.quality?.requiredCommands || ['npm run build'];
const optionalCommands = profile.quality?.optionalCommands || [];

if (writeModeEnabled) {
  for (const command of requiredCommands) {
    const gate = run(command);
    operations.push({ step: 'quality_gate', command, status: gate.ok ? 'ok' : 'failed' });
    if (!gate.ok) {
      qualityGateFailed = true;
      errors.push(`Quality gate failed: ${command}`);
      if (gate.stdout) warnings.push(gate.stdout);
      if (gate.stderr) warnings.push(gate.stderr);
      break;
    }
  }

  if (!qualityGateFailed) {
    for (const command of optionalCommands) {
      const gate = run(command);
      operations.push({ step: 'quality_gate_optional', command, status: gate.ok ? 'ok' : 'warning' });
      if (!gate.ok) {
        warnings.push(`Optional quality gate failed: ${command}`);
        if (gate.stdout) warnings.push(gate.stdout);
        if (gate.stderr) warnings.push(gate.stderr);
      }
    }
  }
} else {
  operations.push({ step: 'quality_gate', status: 'skipped', detail: `Skipped in ${mode} mode.` });
}

if (writeModeEnabled && qualityGateFailed) {
  const output = {
    status: 'error',
    mode,
    branch,
    operations,
    warnings,
    errors,
    nextActions: ['Fix quality gate failures, then rerun session-end with --confirm-write.']
  };

  if (args.json) {
    console.log(JSON.stringify(output, null, 2));
  } else {
    console.error('❌ Session-end aborted due to quality gate failure.');
    errors.forEach(item => console.error(`- ${item}`));
  }

  process.exit(EXIT.QUALITY_GATE_FAILURE);
}

// Stale priorities check — runs in all modes; blocks write, warns in plan/dry-run
if (fs.existsSync('CLAUDE.md')) {
  const claudeForCheck = fs.readFileSync('CLAUDE.md', 'utf8');
  const staleItems = detectStalePriorities(claudeForCheck);
  if (staleItems.length > 0) {
    const detail = staleItems.join(', ');
    const staleMsg = `Stale "Next Session Priorities" — these completed items are still listed as priorities: ${detail}. Update CLAUDE.md § Next Session Priorities before closing.`;
    operations.push({ step: 'priorities_freshness', status: writeModeEnabled ? 'error' : 'warning', detail });
    if (writeModeEnabled) {
      errors.push(staleMsg);
      const output = {
        status: 'error',
        mode,
        branch,
        operations,
        warnings,
        errors,
        nextActions: ['Update CLAUDE.md ## Next Session Priorities to reflect current work state, then rerun session-end.']
      };
      if (args.json) {
        console.log(JSON.stringify(output, null, 2));
      } else {
        console.error('❌ Session-end aborted: stale Next Session Priorities detected.');
        errors.forEach(item => console.error(`- ${item}`));
      }
      process.exit(EXIT.QUALITY_GATE_FAILURE);
    } else {
      warnings.push(staleMsg);
    }
  } else {
    operations.push({ step: 'priorities_freshness', status: 'ok' });
  }
}

if (writeModeEnabled) {
  if (!fs.existsSync(logDir)) fs.mkdirSync(logDir, { recursive: true });

  const claudePath = 'CLAUDE.md';
  const claudeContent = fs.readFileSync(claudePath, 'utf8');
  const notesPath = path.join('.claude', 'session-notes.md');

  const notesContent = fs.existsSync(notesPath) ? fs.readFileSync(notesPath, 'utf8') : '';

  // Require a real session summary before writing anything.
  // Create .claude/session-notes.md from .claude/session-notes-template.md and fill in ## Summary.
  const sessionSummary = extractSessionSummary(notesContent);
  if (!sessionSummary) {
    const hint = notesContent
      ? 'session-notes.md exists but ## Summary is missing or still a placeholder.'
      : 'session-notes.md not found.';
    const summaryError = `${hint} Copy .claude/session-notes-template.md → .claude/session-notes.md, fill in ## Summary with a one-line description of what was done, then rerun.`;
    errors.push(summaryError);
    const earlyOutput = { status: 'error', mode, branch, operations, warnings, errors, nextActions: ['Write session-notes.md with a real ## Summary line, then rerun session-end:write.'] };
    if (args.json) { console.log(JSON.stringify(earlyOutput, null, 2)); } else { console.error('❌ Session-end aborted: no session summary.'); errors.forEach(e => console.error(`- ${e}`)); }
    process.exit(EXIT.QUALITY_GATE_FAILURE);
  }

  // Fresh-eyes review gate (#82): the independent review itself is an agent-level step
  // the script can't run, so it enforces the evidence instead — a close cannot be
  // written unless the notes record the review outcome under ## Review.
  const reviewResult = extractReviewResult(notesContent);
  if (!reviewResult) {
    const reviewError = 'session-notes.md has no recorded review outcome under ## Review. Run an INDEPENDENT fresh-eyes review of this session\'s cumulative diff (/code-review or a fresh-context subagent — not a self-review), fix any blocking findings, record the outcome under ## Review, then rerun. Sessions with no reviewable diff record "Skipped — <reason>".';
    errors.push(reviewError);
    const earlyOutput = { status: 'error', mode, branch, operations, warnings, errors, nextActions: ['Run the independent review, record its outcome in session-notes.md ## Review, then rerun session-end:write.'] };
    if (args.json) { console.log(JSON.stringify(earlyOutput, null, 2)); } else { console.error('❌ Session-end aborted: no fresh-eyes review recorded.'); errors.forEach(e => console.error(`- ${e}`)); }
    process.exit(EXIT.QUALITY_GATE_FAILURE);
  }
  operations.push({ step: 'review_gate', status: 'ok', detail: reviewResult.split('\n')[0] });

  const logContent = buildSessionLog({
    branch,
    headHash,
    date: today,
    isoDate: new Date().toISOString(),
    airtable: args.airtable,
    claudeContent,
    notesPath,
    reviewResult,
  });
  fs.writeFileSync(logPath, logContent);
  operations.push({ step: 'session_log', status: 'written', detail: logPath });

  // Remove session notes after incorporating them into the log
  if (fs.existsSync(notesPath)) {
    fs.unlinkSync(notesPath);
    operations.push({ step: 'session_notes', status: 'consumed', detail: notesPath });
  }

  const withFreshLastSession = upsertClaudeLastSession(claudeContent, today, sessionSummary);
  const claudeUpdate = ensureNextSessionBlock(withFreshLastSession);
  if (claudeUpdate.changed || claudeUpdate.content !== claudeContent) {
    fs.writeFileSync(claudePath, claudeUpdate.content);
    operations.push({ step: 'claude_priorities', status: 'updated' });
  } else {
    operations.push({ step: 'claude_priorities', status: 'unchanged' });
  }

  const markerFiles = (profile.docs?.managedFiles || []).filter(file => file !== 'CLAUDE.md');
  for (const file of markerFiles) {
    if (!fs.existsSync(file)) {
      warnings.push(`Managed file missing: ${file}`);
      continue;
    }

    const content = fs.readFileSync(file, 'utf8');
    const blockUpdate = upsertSessionProtocolBlock(content, {
      sessionId: ts,
      date: new Date().toISOString(),
      mode
    }, sessionBlockMarkers);
    if (blockUpdate.changed) {
      fs.writeFileSync(file, blockUpdate.content);
      operations.push({ step: 'doc_marker', file, status: 'updated' });
    } else {
      operations.push({ step: 'doc_marker', file, status: 'unchanged' });
    }
  }

  if (args.airtable || profile.airtable?.enabledByDefault) {
    warnings.push('Airtable update is currently a placeholder and did not mutate external state.');
    operations.push({ step: 'airtable', status: 'warning', detail: 'placeholder only' });
  }

  const changedPaths = collectChangedPaths();
  const isAllowedByPattern = filePath => matchesAnyPattern(filePath, allowedChangedPathPatterns);
  const allowedPaths = changedPaths.filter(filePath => (
    plannedManagedFiles.has(filePath)
    || filePath === logPath
    || isAllowedArtifact(filePath)
    || isAllowedByPattern(filePath)
  ));
  const blockedPaths = changedPaths.filter(filePath => !(
    plannedManagedFiles.has(filePath)
    || filePath === logPath
    || isAllowedArtifact(filePath)
    || isAllowedByPattern(filePath)
  ));

  if (blockedPaths.length > 0) {
    errors.push(`Unexpected changed files outside protocol scope: ${blockedPaths.join(', ')}`);
    const output = {
      status: 'error',
      mode,
      branch,
      operations,
      warnings,
      errors,
      nextActions: ['Review changed files and update protocol profile scope if intended.']
    };
    if (args.json) {
      console.log(JSON.stringify(output, null, 2));
    } else {
      console.error('❌ Session-end aborted due to unexpected changed files.');
      errors.forEach(item => console.error(`- ${item}`));
    }
    process.exit(EXIT.POLICY_VIOLATION);
  }

  if (allowedPaths.length > 0) {
    const addResult = run(`git add ${allowedPaths.map(shellQuote).join(' ')}`);
    if (!addResult.ok) {
      errors.push('git add failed for allowed session-end paths.');
      if (addResult.stdout) warnings.push(addResult.stdout);
      if (addResult.stderr) warnings.push(addResult.stderr);
      const output = {
        status: 'error',
        mode,
        branch,
        operations,
        warnings,
        errors,
        nextActions: ['Resolve git add path errors, then rerun session-end write mode.']
      };
      if (args.json) {
        console.log(JSON.stringify(output, null, 2));
      } else {
        console.error('❌ Session-end aborted due to git add failure.');
        errors.forEach(item => console.error(`- ${item}`));
      }
      process.exit(EXIT.CRITICAL_FAILURE);
    }
  }

  const staged = run('git diff --cached --name-only');
  if (!staged.ok || !staged.stdout) {
    warnings.push('No staged changes detected; skipping commit and push.');
    operations.push({ step: 'git_commit', status: 'skipped', detail: 'no staged changes' });
  } else {
    const commitTemplate = profile.sessionEnd?.commitMessageTemplate || 'docs(session): {date} session wrap';
    const commitMessage = commitTemplate.replace('{date}', today);
    const commitResult = run(`git commit -m ${shellQuote(commitMessage)}`);
    if (!commitResult.ok) {
      errors.push('git commit failed.');
      if (commitResult.stdout) warnings.push(commitResult.stdout);
      if (commitResult.stderr) warnings.push(commitResult.stderr);
      process.exit(EXIT.CRITICAL_FAILURE);
    }
    operations.push({ step: 'git_commit', status: 'ok', detail: commitMessage });

    if (args.yes && profile.sessionEnd?.autoPushAllowed !== false) {
      const pushResult = run(`git push ${shellQuote(profile.git.defaultPushRemote || 'origin')} ${shellQuote(branch)}`);
      if (!pushResult.ok) {
        errors.push('git push failed.');
        if (pushResult.stdout) warnings.push(pushResult.stdout);
        if (pushResult.stderr) warnings.push(pushResult.stderr);
        process.exit(EXIT.CRITICAL_FAILURE);
      }
      operations.push({ step: 'git_push', status: 'ok', detail: `${profile.git.defaultPushRemote || 'origin'} ${branch}` });
    } else {
      operations.push({ step: 'git_push', status: 'skipped', detail: 'Push requires --yes and autoPushAllowed=true in profile.' });
      warnings.push('Push skipped by policy. Use --yes and set sessionEnd.autoPushAllowed=true to enable.');
    }
  }
}

if (mode === 'dry-run') {
  operations.push({ step: 'planned_outputs', status: 'ok', detail: `Would write session log to ${logPath}` });
  operations.push({ step: 'planned_outputs', status: 'ok', detail: 'Would update CLAUDE.md Next Session Priorities block if missing.' });
  operations.push({ step: 'planned_outputs', status: 'ok', detail: 'Would upsert single session protocol blocks in managed docs.' });
}

const status = errors.length > 0 ? 'error' : warnings.length > 0 ? 'warning' : 'ok';
const output = {
  status,
  mode,
  branch,
  operations,
  warnings,
  errors,
  nextActions: [
    mode === 'plan'
      ? 'Rerun with --confirm-write to execute writes.'
      : 'Review warnings before closing session.',
    'If push is required, rerun with --confirm-write --yes and enable autoPushAllowed in profile.'
  ]
};

if (args.json) {
  console.log(JSON.stringify(output, null, 2));
} else {
  console.log(`\n## Session End — ${today}\n`);
  console.log(`Mode: ${mode}`);
  console.log(`Branch: ${branch}`);
  operations.forEach(op => {
    const descriptor = op.command ? `${op.step} (${op.command})` : op.step;
    console.log(`- ${descriptor}: ${op.status}${op.detail ? ` — ${op.detail}` : ''}`);
  });

  if (warnings.length > 0) {
    console.log('\nWarnings:');
    warnings.forEach(item => console.log(`- ${item}`));
  }

  if (errors.length > 0) {
    console.log('\nErrors:');
    errors.forEach(item => console.log(`- ${item}`));
  }
}

if (errors.length > 0) {
  process.exit(EXIT.CRITICAL_FAILURE);
}

process.exit(EXIT.SUCCESS);
